#!/bin/sh
# Picks a random background image for ghostty and writes a machine-local
# config snippet for the next launch. The optional theme argument selects
# the image set and how it is displayed:
#   firefly (default) — full-bleed night photos from images/firefly
#   ink_painting      — paper-tinted art from images/ink_painting-tinted
#                       (generated by tint-bg-images.py; after adding new
#                       images run: uv run ~/dotfiles/ghostty/tint-bg-images.py)
# Note: switching sets here does NOT switch the ghostty color theme; that
# lives in ghostty/config (theme = ...).

set -e

THEME="${1:-firefly}"
BASE="$HOME/dotfiles/ghostty/images"
OUTPUT="$HOME/.config/ghostty/background.conf"

case "$THEME" in
  firefly)
    IMAGES_DIR="$BASE/firefly"
    FIT=cover
    OPACITY=0.4
    ;;
  ink_painting)
    IMAGES_DIR="$BASE/ink_painting-tinted"
    FIT=contain
    OPACITY=0.4
    ;;
  *)
    echo "unknown theme: $THEME (expected: firefly | ink_painting)" >&2
    exit 1
    ;;
esac

mkdir -p "$(dirname "$OUTPUT")"

# awkの引数なしsrand()は秒単位の時刻シードで、macOSのawkは近い時刻から
# ほぼ同じ乱数列を作るため、実行のたびに同じ画像ばかり選ばれてしまう。
# /dev/urandomからシードを取って毎回独立に選ぶ。
seed=$(od -An -N4 -tu4 /dev/urandom | tr -d ' ')
chosen=$(
  find "$IMAGES_DIR" -type f \
    \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) 2>/dev/null \
  | awk -v seed="$seed" 'BEGIN{srand(seed)} {a[NR]=$0} END{if(NR>0)print a[int(rand()*NR)+1]}'
)

if [ -n "$chosen" ]; then
  cat > "$OUTPUT" <<EOF
background-image = $chosen
background-image-position = center
background-image-fit = $FIT
background-image-opacity = $OPACITY
EOF
  echo "ghostty background -> $(basename "$chosen")"
  echo "Reload with cmd+shift+, or open a new ghostty window."
fi
